# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - main
    - dev
    - azure-pipelines

pr:
  branches:
    include:
    - main
    - dev

resources:
- repo: self

variables:
  version: '0.1'
  longTag: '$(version).$(Build.BuildId)'
  REGISTRY_MAPPED: $(Registry)

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/Dockerfile'
        tags: |
          $(version)
          $(longTag)
