# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - main
    - dev
    - azure-pipelines

pr:
  branches:
    include:
    - main
    - dev

resources:
- repo: self

variables:
  buildNumber: $(Build.BuildID)
  REGISTRY_MAPPED: $(Registry)

pool: Default

stages:
- stage: Build
  displayName: Build image
  jobs:
  - task: PowerShell@2
    displayName: Set the version
    inputs:
      targetType: 'inline'
      script: |
        $shortTag = (Get-Content ..\..\build.config.json | ConvertFrom-Json).Version
        $longTag = $(shortTag).$(buildNumber)
        Write-Host "Setting the short tag to '$shortTag'."
        Write-Host "Setting the long tag to '$longTag'."
        Write-Host "##vso[task.setvariable variable=shortTag]$shortTag"
        Write-Host "##vso[task.setvariable variable=longTag]$longTag"
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        arguments: '--build-arg VERSION=$(longTag) --target build'
        dockerfile: '$(Build.SourcesDirectory)/src/Dockerfile'
        repository: 'nwesitecore/sitecore-trekroner'
        tags: |
          $(shortTag)
          $(longTag)

- stage: Push
  dependsOn:
  - Build
  condition: ne(variables['Build.Reason'], 'PullRequest')

  jobs:
    - job: Push
      displayName: Push image
      steps:
      - task: Docker@2
        displayName: Login to registry
        inputs:
          containerRegistry: '$(RegistryServiceConnection)'
          command: 'login'
      - task: Docker@2
        inputs:
          containerRegistry: '$(RegistryServiceConnection)'
          repository: 'nwesitecore/sitecore-trekroner'
          command: 'push'
          tags: |
            $(shortTag)
            $(longTag)
