# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - main
    - dev
    - azure-pipelines

pr:
  branches:
    include:
    - main
    - dev

resources:
- repo: self

variables:
  version: '0.1'
  longTag: '$(version).$(Build.BuildId)'
  REGISTRY_MAPPED: $(Registry)

pool: Default

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/Dockerfile'
        repository: 'nwesitecore/sitecore-trekroner'
        tags: |
          $(version)
          $(longTag)

- stage: Push
  dependsOn:
  - Build
  condition: ne(variables['Build.Reason'], 'PullRequest')

  jobs:
    - job: Push
      displayName: Push image
      steps:
      - task: Docker@2
        displayName: Login to registry
        inputs:
          containerRegistry: '$(RegistryServiceConnection)'
          command: 'login'
      - task: Docker@2
        inputs:
          containerRegistry: '$(RegistryServiceConnection)'
          repository: 'nwesitecore/sitecore-trekroner'
          command: 'push'
          tags: |
            $(version)
            $(longTag)
